name: Nightly EDK2 OVMF Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    name: Nightly EDK2 OVMF Build
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git wget python acpica nasm

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Rebuild
        run: |
          set -ex

          GCC_VERSION=15.2.0

          for i in aarch64 loongarch64 riscv64; do
              wget https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/$GCC_VERSION/x86_64-gcc-$GCC_VERSION-nolibc-$i-linux.tar.gz
              tar -xf x86_64-gcc-$GCC_VERSION-nolibc-$i-linux.tar.gz
              export PATH="$(pwd -P)"/gcc-$GCC_VERSION-nolibc/$i-linux/bin:"$PATH"
          done

          git clone --recursive --depth=1 https://github.com/tianocore/edk2.git

          ( cd edk2 && patch -p1 <../ovmf.patch )

          export PACKAGES_PATH="$(pwd -P)"/edk2

          export GCC_AARCH64_PREFIX=aarch64-linux-
          export GCC_LOONGARCH64_PREFIX=loongarch64-linux-
          export GCC_RISCV64_PREFIX=riscv64-linux-

          set +e
          . edk2/edksetup.sh
          set -e
          make -C edk2/BaseTools

          build -b RELEASE -t GCC -a AARCH64 -p ArmVirtPkg/ArmVirtQemu.dsc
          build -b RELEASE -t GCC -a LOONGARCH64 -p OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc
          build -b RELEASE -t GCC -a RISCV64 -p OvmfPkg/RiscVVirt/RiscVVirtQemu.dsc
          build -b RELEASE -t GCC -a X64 -p OvmfPkg/OvmfPkgX64.dsc -D FD_SIZE_2MB

          mkdir -p output

          cp Build/ArmVirtQemu-AArch64/RELEASE_GCC/FV/QEMU_EFI.fd  output/ovmf-code-aarch64.fd
          cp Build/ArmVirtQemu-AArch64/RELEASE_GCC/FV/QEMU_VARS.fd output/ovmf-vars-aarch64.fd

          cp Build/LoongArchVirtQemu/RELEASE_GCC/FV/QEMU_EFI.fd  output/ovmf-code-loongarch64.fd
          cp Build/LoongArchVirtQemu/RELEASE_GCC/FV/QEMU_VARS.fd output/ovmf-vars-loongarch64.fd

          cp Build/RiscVVirtQemu/RELEASE_GCC/FV/RISCV_VIRT_CODE.fd output/ovmf-code-riscv64.fd
          cp Build/RiscVVirtQemu/RELEASE_GCC/FV/RISCV_VIRT_VARS.fd output/ovmf-vars-riscv64.fd

          cp Build/OvmfX64/RELEASE_GCC/FV/OVMF_CODE.fd output/ovmf-code-x86_64.fd
          cp Build/OvmfX64/RELEASE_GCC/FV/OVMF_VARS.fd output/ovmf-vars-x86_64.fd

          # Support for IA32 was dropped upstream
          wget -O output/ovmf-code-ia32.fd https://github.com/osdev0/edk2-ovmf-nightly/releases/download/nightly-2025-09-09/ovmf-code-ia32.fd
          wget -O output/ovmf-vars-ia32.fd https://github.com/osdev0/edk2-ovmf-nightly/releases/download/nightly-2025-09-09/ovmf-vars-ia32.fd


      - name: Set TAG_DATE variable
        run: echo "TAG_DATE=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV

      - name: Rename output directory
        run: mv output edk2-ovmf

      - name: Create release tarball
        run: |
          set -e
          dd if=/dev/zero of=edk2-ovmf/ovmf-code-aarch64.fd bs=1 count=0 seek=67108864
          dd if=/dev/zero of=edk2-ovmf/ovmf-code-riscv64.fd bs=1 count=0 seek=33554432
          dd if=/dev/zero of=edk2-ovmf/ovmf-vars-aarch64.fd bs=1 count=0 seek=67108864
          dd if=/dev/zero of=edk2-ovmf/ovmf-vars-riscv64.fd bs=1 count=0 seek=33554432
          tar -zcvf edk2-ovmf.tar.gz edk2-ovmf
          tar -Jcvf edk2-ovmf.tar.xz edk2-ovmf

      - name: Tag new nightly release
        run: git tag nightly-$TAG_DATE && git push --tags

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          name: Nightly Build ${{ env.TAG_DATE }}
          tag_name: nightly-${{ env.TAG_DATE }}
          body: Images of an up to date EDK2 OVMF nightly build.
          files: |
            edk2-ovmf.tar.gz
            edk2-ovmf.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
